using System;
using System.Collections.Generic;
using UnityEngine;

namespace CraDev
{
    public enum Language { Uz, En }

    /// <summary>
    /// O'yin matnlari ikki tilda: o'zbekcha (standart) va inglizcha. Til PlayerPrefs'da saqlanadi.
    /// Matn kalit bo'yicha olinadi: <c>Loc.T("menu.enter")</c>. Til almashsa <see cref="Changed"/> chaqiriladi,
    /// <see cref="LocalizedText"/> komponentlari o'zi yangilanadi.
    /// </summary>
    public static partial class Loc
    {
        const string PrefKey = "cradev.language";
        static Language? current;

        public static event Action Changed;

        public static Language Current
        {
            get
            {
                current ??= PlayerPrefs.GetString(PrefKey, "uz") == "en" ? Language.En : Language.Uz;
                return current.Value;
            }
            set
            {
                if (Current == value)
                    return;
                current = value;
                PlayerPrefs.SetString(PrefKey, value == Language.En ? "en" : "uz");
                PlayerPrefs.Save();
                Changed?.Invoke();
            }
        }

        public static string Code => Current == Language.En ? "EN" : "UZ";

        public static string T(string key)
        {
            if (!Table.TryGetValue(key, out var pair) && (extra == null || !extra.TryGetValue(key, out pair)))
            {
                Debug.LogWarning("[CraDev] Tarjima yo'q: " + key);
                return key;
            }
            return Current == Language.En ? pair.en : pair.uz;
        }

        /// <summary>Formatlangan matn: <c>Loc.F("create.welcome", nickname)</c>.</summary>
        public static string F(string key, params object[] args) => string.Format(T(key), args);

        /// <summary>Harflar orasini ochadi ("XUSH" -> "X U S H"): Text'da harf oralig'i sozlamasi yo'q.</summary>
        public static string Spaced(string text) => string.Join(" ", text.ToCharArray()).Replace("   ", "     ");

        /// <summary>Qo'shimcha matnlar: <c>Loc.*.cs</c> partial fayllari o'z jadvalini <see cref="Register"/> orqali qo'shadi.</summary>
        static Dictionary<string, (string uz, string en)> extra;

        static Dictionary<string, (string uz, string en)> Register(Dictionary<string, (string uz, string en)> table)
        {
            extra ??= new Dictionary<string, (string uz, string en)>();
            foreach (var pair in table)
                extra[pair.Key] = pair.Value;
            return table;
        }

        /// <summary>Kalit jadvalda bormi (test va zaxira matnlar uchun).</summary>
        public static bool Has(string key) => Table.ContainsKey(key) || (extra != null && extra.ContainsKey(key));

        static readonly Dictionary<string, (string uz, string en)> Table = new Dictionary<string, (string, string)>
        {
            // ---------------- Umumiy
            ["lobby.caption"] = ("Sizning yangi dunyongiz", "Your new world"),
            ["settings.weather"] = ("Lobbi ob-havosi", "Lobby weather"),
            ["weather.0"] = ("Soat bo‘yicha", "Local clock"),
            ["weather.1"] = ("Bulutli", "Cloudy"),
            ["weather.2"] = ("Yomg‘irli", "Rainy"),
            ["weather.3"] = ("Qorli", "Snowy"),
            ["settings.atmosphere"] = ("Fon animatsiyasi", "Background animation"),
            ["lobby.online"] = ("Onlayn", "Online"),
            ["lobby.offline"] = ("Oflayn", "Offline"),
            ["lobby.promo"] = ("Yangi sarguzasht\nseni kutmoqda", "Your next adventure\nawaits"),
            ["lobby.promo_hint"] = ("Do‘stlaring bilan birga\nkashf et", "Explore together\nwith your friends"),
            ["lobby.with_friends"] = ("Do‘stlar bilan", "With friends"),
            ["lobby.together"] = ("Birga yanada qiziqarli", "Better together"),
            ["lobby.your_world"] = ("O‘z dunyong", "Your world"),
            ["lobby.possibilities"] = ("Cheksiz imkoniyatlar", "Endless possibilities"),
            ["lobby.enter"] = ("NewWorldga kirish", "Enter NewWorld"),
            ["lobby.enter_hint"] = ("Sarguzasht shu yerdan boshlanadi", "Your adventure starts here"),
            ["lobby.profile_hint"] = ("Shaxsiy profil · Sozlamalar", "Your profile · Settings"),
            ["lobby.world_pending"] = ("NewWorld dunyosi hali ulanmagan. Kirish shu tugma orqali bo'ladi.", "The NewWorld game world is not connected yet. This is where you will enter."),
            ["lobby.friends_hint"] = ("Do'stlaringiz bilan birga", "Together with your friends"),
            ["lobby.tool.find"] = ("Yangi do'st qidirish", "Find new friends"),
            ["lobby.tool.online"] = ("Faqat onlayn do'stlar", "Online friends only"),
            ["lobby.tool.remove"] = ("Do'stlarni boshqarish", "Manage friends"),
            ["lobby.tool.requests"] = ("Do'stlik so'rovlari", "Friend requests"),
            ["lobby.tool.refresh"] = ("Ro'yxatni yangilash", "Refresh list"),
            ["lobby.friend_count"] = ("{0} onlayn / {1} do'st", "{0} online / {1} friends"),
            ["lobby.empty_friends"] = ("Hozircha do'stlar yo'q. Yuqoridagi + orqali do'st qidiring.", "No friends yet. Use + above to find someone."),
            ["lobby.empty_online"] = ("Hozir onlayn do'stlar yo'q.", "No friends online right now."),
            ["lobby.empty_requests"] = ("Do'stlik so'rovlari yo'q.", "No friend requests."),
            ["lobby.remove_confirm"] = ("{0} bilan do'stlikni yoki so'rovni bekor qilasizmi?", "Remove the friendship or request with {0}?"),
            ["common.cancel"] = ("Bekor qilish", "Cancel"),
            ["world.hud.controls"] = ("WASD — yurish  ·  Shift — yugurish  ·  Ctrl / C — cho'kkalash  ·  Space — sakrash  ·  Esc — sozlamalar", "WASD — move  ·  Shift — sprint  ·  Ctrl / C — crouch  ·  Space — jump  ·  Esc — settings"),
            ["world.hud.standing"] = ("Turgan", "Standing"),
            ["world.hud.walking"] = ("Yurish", "Walking"),
            ["world.hud.running"] = ("Yugurish", "Sprinting"),
            ["world.hud.crouching"] = ("Cho'kkalash", "Crouching"),
            ["world.hud.airborne"] = ("Havoda", "Airborne"),
            ["world.hud.north"] = ("SH", "N"),
            ["world.settings.title"] = ("Dunyo sozlamalari", "World settings"),
            ["world.settings.subtitle"] = ("Harakat va kamera — faqat o'yin olami uchun", "Movement and camera — game world only"),
            ["world.settings.resume"] = ("Davom etish", "Resume"),
            ["world.settings.sensitivity"] = ("Sichqoncha sezgirligi", "Mouse sensitivity"),
            ["world.settings.fov"] = ("Ko'rish maydoni", "Field of view"),
            ["world.settings.invert"] = ("Sichqoncha Y o'qini teskari qilish", "Invert mouse Y axis"),
            ["world.settings.headbob"] = ("Yurganda kamera tebranishi", "Camera bob while walking"),
            ["world.settings.crouch"] = ("Cho'kkalashni tugma bilan yoqish/o'chirish", "Toggle crouch instead of holding"),
            ["world.settings.reset"] = ("Asliga qaytarish", "Restore defaults"),
            ["world.settings.lobby"] = ("Lobbyga qaytish", "Return to lobby"),
            ["world.settings.saved"] = ("O'zgarishlar avtomatik saqlanadi", "Changes save automatically"),
            ["party.leave"] = ("Lobbyni tark etish", "Leave party"),
            ["party.leave_confirm"] = ("Guruhdan chiqasizmi? Mezbon chiqsa, guruh yopiladi.", "Leave this party? If the host leaves, the party closes."),
            ["party.invite"] = ("Lobbyga taklif", "Party invitation"),
            ["party.invite_from"] = ("{0} sizni lobbysiga chaqiryapti.", "{0} invited you to their lobby."),
            ["party.accept"] = ("Qo'shilish", "Join"),
            ["party.decline"] = ("Rad etish", "Decline"),
            ["party.sent"] = ("Lobbyga taklif yuborildi (60 soniya).", "Party invitation sent (60 seconds)."),
            ["party.joined"] = ("Lobbyga qo'shildingiz.", "You joined the party."),
            ["party.error.network"] = ("Server bilan aloqa yo'q. Qayta urinib ko'ring.", "Cannot reach the server. Please try again."),
            ["party.error.host_only"] = ("Faqat mezbon do'stlarini chaqira oladi.", "Only the host can invite friends."),
            ["party.error.friends_only"] = ("Faqat do'st yoki guruhdoshni chaqirish mumkin.", "Only friends or group members can be invited."),
            ["party.error.already_joined"] = ("Bu do'stingiz allaqachon lobbyda.", "This friend is already in the lobby."),
            ["party.error.party_full"] = ("Barcha 5 o'rin band yoki taklif bilan saqlangan.", "All 5 seats are occupied or reserved by invitations."),
            ["party.error.no_invite"] = ("Taklifning vaqti tugagan yoki lobby yopilgan.", "The invitation expired or the lobby closed."),
            ["party.error.leave_first"] = ("Avval hozirgi guruhdan chiqing.", "Leave your current party first."),
            ["party.error.too_many_invites"] = ("Bu do'stingizda kutilayotgan takliflar ko'p.", "This friend has too many pending invitations."),
            ["party.error.too_many_requests"] = ("Bir oz kuting va qayta urinib ko'ring.", "Please wait a moment and try again."),
            ["party.error.unauthorized"] = ("Profilni qayta tekshirish kerak.", "Your session needs to be verified again."),
            ["common.quit"] = ("Chiqish", "Quit"),
            ["common.ok"] = ("Tushunarli", "Got it"),
            ["common.soon"] = ("Tez orada", "Coming soon"),
            ["common.online"] = ("Onlayn", "Online"),
            ["common.offline"] = ("Oflayn", "Offline"),
            ["common.connecting"] = ("Ulanmoqda…", "Connecting…"),
            ["common.server_error"] = ("Server xatosi", "Server error"),
            ["loading.loading"] = ("YUKLANMOQDA", "LOADING"),
            ["loading.ready"] = ("TAYYOR", "READY"),

            // ---------------- Lobby: umumiy (navigatsiya, profil menyusi, xabarlar)
            ["nav.home"] = ("Bosh sahifa", "Home"),
            ["nav.world"] = ("Dunyo", "World"),
            ["nav.friends"] = ("Do'stlar", "Friends"),
            ["nav.top"] = ("Top-lar", "Leaderboard"),
            ["nav.settings"] = ("Sozlamalar", "Settings"),
            ["menu.wardrobe"] = ("Garderob", "Wardrobe"),
            ["menu.customize"] = ("Personajni sozlash", "Customize character"),
            ["menu.settings"] = ("Sozlamalar", "Settings"),
            ["menu.quit"] = ("Chiqish", "Quit"),
            ["menu.zone_soon"] = ("{0}: tez orada ochiladi", "{0}: opening soon"),
            ["menu.no_notifications"] = ("Yangi bildirishnomalar yo'q", "No new notifications"),
            ["menu.quit_title"] = ("Chiqasizmi?", "Quit game?"),
            ["menu.quit_message"] = ("Virtual dunyodan chiqmoqchimisiz?", "Are you sure you want to leave the virtual world?"),
            ["menu.profile_missing_title"] = ("Profil topilmadi", "Profile not found"),
            ["menu.profile_missing_message"] = ("Profilingiz serverda yo'q. Davom etish uchun yangi qahramon yarating.",
                "Your player profile no longer exists on the server. Create a new character to continue."),
            ["menu.create_character"] = ("Qahramon yaratish", "Create character"),
            ["menu.offline"] = ("Serverga ulanib bo'lmadi. Qayta urinib ko'ring.", "Can't reach the server. Please try again."),

            // ---------------- Bosh sahifa
            ["home.subtitle"] = ("O'z dunyongni kashf et", "Discover your own world"),
            ["home.enter"] = ("Kirish", "Enter"),
            ["home.tagline1"] = ("Cheksiz imkoniyatlar", "Endless possibilities"),
            ["home.tagline2"] = ("Bitta virtual dunyoda", "In one virtual world"),
            ["home.event_today"] = ("Bugungi tadbir", "Today's event"),
            ["home.event_next"] = ("Keyingi tadbir", "Next event"),
            ["home.event_none"] = ("Tadbirlar tez orada", "Events coming soon"),
            ["home.card.world"] = ("Dunyo", "World"),
            ["home.card.world.sub"] = ("Erkin sayohat", "Free roam"),

            // ---------------- Dunyo xaritasi
            ["world.title"] = ("Dunyo xaritasi", "World map"),
            ["world.subtitle"] = ("Istalgan joyga boring", "Go anywhere you like"),
            ["world.search"] = ("Joylashuvni qidirish...", "Search for a place..."),
            ["world.cat.all"] = ("Barchasi", "All"),
            ["world.cat.housing"] = ("Turar joylar", "Residences"),
            ["world.cat.events"] = ("Tadbirlar", "Events"),
            ["world.cat.services"] = ("Xizmatlar", "Services"),
            ["world.center"] = ("Shahar markazi", "City center"),
            ["world.center.sub"] = ("NewWorld minorasi va maydon", "NewWorld tower and square"),
            ["world.online"] = ("Hozir onlayn: {0}", "Online now: {0}"),
            ["world.online_unknown"] = ("Onlayn soni aniqlanmoqda…", "Counting players online…"),
            ["world.no_results"] = ("Hech narsa topilmadi", "Nothing found"),

            // ---------------- Garderob
            ["wardrobe.title"] = ("Garderob", "Wardrobe"),
            ["wardrobe.subtitle"] = ("O'zingizning uslubingizni yarating", "Create your own style"),
            ["wardrobe.cat.clothes"] = ("Kiyimlar", "Clothes"),
            ["wardrobe.cat.shoes"] = ("Poyabzallar", "Shoes"),
            ["wardrobe.cat.accessories"] = ("Aksessuarlar", "Accessories"),
            ["wardrobe.cat.hair"] = ("Soch turmagi", "Hair"),
            ["wardrobe.cat.looks"] = ("Obrazlar", "Looks"),
            ["wardrobe.cat.saved"] = ("Saqlanganlar", "Saved"),
            ["wardrobe.style.all"] = ("Hammasi", "All"),
            ["wardrobe.style.suit"] = ("Kostyumlar", "Suits"),
            ["wardrobe.style.sport"] = ("Sportcha", "Sporty"),
            ["wardrobe.style.casual"] = ("Kundalik", "Casual"),
            ["wardrobe.style.special"] = ("Maxsus", "Special"),
            ["wardrobe.slot.top"] = ("Ustki kiyim", "Tops"),
            ["wardrobe.slot.bottom"] = ("Shimlar", "Bottoms"),
            ["wardrobe.save"] = ("Saqlash", "Save"),
            ["wardrobe.saved"] = ("Kiyim saqlandi", "Outfit saved"),
            ["wardrobe.save_failed"] = ("Saqlanmadi. Server bilan aloqani tekshirib, qayta urinib ko'ring.", "Not saved. Check the server connection and try again."),
            ["wardrobe.original"] = ("Asl kiyim", "Original"),
            ["wardrobe.original_hair"] = ("Asl soch rangi", "Original hair color"),
            ["wardrobe.unsaved_title"] = ("O'zgarishlar saqlanmagan", "Unsaved changes"),
            ["wardrobe.unsaved_message"] = ("Yangi kiyimni saqlaysizmi?", "Do you want to save your new outfit?"),
            ["wardrobe.discard"] = ("Saqlamaslik", "Discard"),
            ["wardrobe.accessories_soon"] = ("Aksessuarlar tez orada qo'shiladi", "Accessories are coming soon"),
            ["wardrobe.hair_unsupported"] = ("Bu avatarda soch rangini o'zgartirib bo'lmaydi", "Hair color can't be changed on this avatar"),
            ["wardrobe.save_look"] = ("Joriy obrazni saqlash", "Save current look"),
            ["wardrobe.look_saved"] = ("Obraz saqlandi", "Look saved"),
            ["wardrobe.looks_full"] = ("Ko'pi bilan 11 ta obraz saqlash mumkin", "You can save up to 11 looks"),
            ["wardrobe.saved_look"] = ("Obraz {0}", "Look {0}"),
            ["wardrobe.color"] = ("Rang", "Color"),
            ["wardrobe.item.top_bomber_black"] = ("Qora bomber", "Black bomber"),
            ["wardrobe.item.top_leather_black"] = ("Qora charm kurtka", "Black leather jacket"),
            ["wardrobe.item.top_leather_brown"] = ("Jigarrang charm kurtka", "Brown leather jacket"),
            ["wardrobe.item.top_knit_white"] = ("Oq trikotaj", "White knit"),
            ["wardrobe.item.top_suede_tan"] = ("Qum rang zamsh", "Tan suede"),
            ["wardrobe.item.top_denim"] = ("Jinsi kurtka", "Denim jacket"),
            ["wardrobe.item.top_blazer_navy"] = ("To'q ko'k pidjak", "Navy blazer"),
            ["wardrobe.item.top_knit_grey"] = ("Kulrang sviter", "Grey sweater"),
            ["wardrobe.item.top_stripes"] = ("Chiziqli", "Striped"),
            ["wardrobe.item.top_plaid_red"] = ("Qizil katak", "Red plaid"),
            ["wardrobe.item.top_camo"] = ("Kamuflyaj", "Camo"),
            ["wardrobe.item.top_sport_red"] = ("Qizil sport", "Red sport"),
            ["wardrobe.item.top_sport_blue"] = ("Ko'k sport", "Blue sport"),
            ["wardrobe.item.top_olive"] = ("Zaytun rang", "Olive"),
            ["wardrobe.item.bottom_jeans_blue"] = ("Ko'k jinsi", "Blue jeans"),
            ["wardrobe.item.bottom_jeans_black"] = ("Qora jinsi", "Black jeans"),
            ["wardrobe.item.bottom_chino_beige"] = ("Bej chinos", "Beige chinos"),
            ["wardrobe.item.bottom_suit_grey"] = ("Kulrang shim", "Grey trousers"),
            ["wardrobe.item.bottom_suit_navy"] = ("To'q ko'k shim", "Navy trousers"),
            ["wardrobe.item.bottom_cargo_black"] = ("Qora kargo", "Black cargo"),
            ["wardrobe.item.bottom_camo"] = ("Kamuflyaj shim", "Camo pants"),
            ["wardrobe.item.bottom_leather"] = ("Charm shim", "Leather pants"),
            ["wardrobe.item.bottom_sport_grey"] = ("Sport shim", "Joggers"),
            ["wardrobe.item.shoes_white"] = ("Oq krossovka", "White sneakers"),
            ["wardrobe.item.shoes_black"] = ("Qora krossovka", "Black sneakers"),
            ["wardrobe.item.shoes_leather_brown"] = ("Jigarrang tufli", "Brown shoes"),
            ["wardrobe.item.shoes_leather_black"] = ("Qora tufli", "Black shoes"),
            ["wardrobe.item.shoes_red"] = ("Qizil krossovka", "Red sneakers"),
            ["wardrobe.item.shoes_blue"] = ("Ko'k krossovka", "Blue sneakers"),
            ["wardrobe.item.shoes_beige"] = ("Bej krossovka", "Beige sneakers"),
            ["wardrobe.item.shoes_camo"] = ("Kamuflyaj", "Camo"),
            ["wardrobe.item.hair_black"] = ("Qora", "Black"),
            ["wardrobe.item.hair_dark_brown"] = ("To'q jigarrang", "Dark brown"),
            ["wardrobe.item.hair_brown"] = ("Jigarrang", "Brown"),
            ["wardrobe.item.hair_auburn"] = ("Qizg'ish jigarrang", "Auburn"),
            ["wardrobe.item.hair_copper"] = ("Mis rang", "Copper"),
            ["wardrobe.item.hair_blond"] = ("Sariq", "Blond"),
            ["wardrobe.item.hair_platinum"] = ("Platina", "Platinum"),
            ["wardrobe.item.hair_grey"] = ("Kumush", "Silver"),
            ["wardrobe.item.hair_blue"] = ("Ko'k", "Blue"),
            ["wardrobe.item.hair_pink"] = ("Pushti", "Pink"),
            ["wardrobe.item.hair_purple"] = ("Binafsha", "Purple"),
            ["wardrobe.look.original"] = ("Asl obraz", "Original look"),
            ["wardrobe.look.casual"] = ("Kundalik", "Casual"),
            ["wardrobe.look.sport"] = ("Sportcha", "Sporty"),
            ["wardrobe.look.formal"] = ("Rasmiy", "Formal"),
            ["wardrobe.look.city"] = ("Shahar", "City"),
            ["wardrobe.look.military"] = ("Harbiy uslub", "Military"),
            ["wardrobe.look.summer"] = ("Yozgi", "Summer"),
            ["wardrobe.look.autumn"] = ("Kuzgi", "Autumn"),
            ["wardrobe.acc.glasses"] = ("Ko'zoynak", "Glasses"),
            ["wardrobe.acc.watch"] = ("Soat", "Watch"),
            ["wardrobe.acc.cap"] = ("Kepka", "Cap"),
            ["wardrobe.acc.bag"] = ("Sumka", "Bag"),
            ["wardrobe.acc.headphones"] = ("Quloqchin", "Headphones"),
            ["wardrobe.acc.chain"] = ("Zanjir", "Chain"),
            ["wardrobe.acc.backpack"] = ("Ryukzak", "Backpack"),
            ["wardrobe.acc.scarf"] = ("Sharf", "Scarf"),

            // ---------------- Magazinlar
            ["lobby.profile.id"] = ("ID", "ID"),
            ["lobby.place.it"] = ("IT Akademiya", "IT Academy"),
            ["lobby.place.medicine"] = ("Tibbiyot markazi", "Medical Center"),
            ["lobby.place.languages"] = ("Til markazi", "Language Hub"),
            ["lobby.place.business"] = ("Biznes maktabi", "Business School"),
            ["lobby.place.art"] = ("San'at studiyasi", "Art Studio"),
            ["lobby.place.science"] = ("Ilm-fan markazi", "Science Center"),
            ["shops.title"] = ("Magazinlar", "Shops"),
            ["shops.subtitle"] = ("Xaridlar uchun barcha bo'limlar", "Explore shopping departments"),
            ["shops.search"] = ("Do'kon turini qidirish...", "Search store categories..."),
            ["shops.see_all"] = ("Barchasini ko'rish", "See all"),
            ["shops.show_less"] = ("Kamroq ko'rsatish", "Show less"),
            ["shops.cat.all"] = ("Barchasi", "All"),
            ["shops.cat.clothes"] = ("Kiyimlar", "Clothing"),
            ["shops.cat.electronics"] = ("Elektronika", "Electronics"),
            ["shops.cat.accessories"] = ("Aksessuarlar", "Accessories"),
            ["shops.cat.home"] = ("Uy jihozlari", "Home goods"),
            ["shops.cat.beauty"] = ("Go'zallik", "Beauty"),
            ["shops.cat.sport"] = ("Sport", "Sport"),
            ["shops.cat.other"] = ("Boshqa", "Other"),
            ["shops.store_soon"] = ("{0} do'koni tez orada ochiladi", "The {0} store opens soon"),
            ["shops.no_results"] = ("Bunday do'kon topilmadi", "No stores found"),
            ["shops.store.clothing"] = ("Kiyimlar", "Clothing"),
            ["shops.store.sportswear"] = ("Sport kiyimlari", "Sportswear"),
            ["shops.store.shoes"] = ("Poyabzallar", "Footwear"),
            ["shops.store.electronics"] = ("Elektronika", "Electronics"),
            ["shops.store.computers"] = ("Kompyuterlar", "Computers"),
            ["shops.store.casual"] = ("Kundalik kiyimlar", "Casual wear"),
            ["shops.store.accessories"] = ("Aksessuarlar", "Accessories"),
            ["shops.store.audio"] = ("Audio jihozlar", "Audio equipment"),
            ["shops.store.home"] = ("Uy jihozlari", "Home goods"),
            ["shops.store.beauty"] = ("Go'zallik", "Beauty"),
            ["shops.store.sports"] = ("Sport anjomlari", "Sports equipment"),
            ["shops.store.gifts"] = ("Sovg'alar", "Gifts"),

            // ---------------- O'quv markazlari
            ["education.title"] = ("O'quv markazlari", "Education centers"),
            ["education.subtitle"] = ("Bilim — kelajak kaliti", "Knowledge is the key to the future"),
            ["education.hero.title"] = ("Ta'lim markazi", "Learning center"),
            ["education.hero.subtitle"] = ("Zamonaviy bilim markazi", "A modern learning center"),
            ["education.visit"] = ("Tashrif buyurish", "Visit"),
            ["education.recommended"] = ("Tavsiya etilgan", "Recommended"),
            ["education.all"] = ("Barchasi", "See all"),
            ["education.cat.all"] = ("Barchasi", "All"),
            ["education.cat.medicine"] = ("Tibbiyot", "Medicine"),
            ["education.cat.technology"] = ("Texnologiya", "Technology"),
            ["education.cat.languages"] = ("Til kurslari", "Language courses"),
            ["education.cat.it"] = ("IT & Dasturlash", "IT & Programming"),
            ["education.cat.business"] = ("Biznes", "Business"),
            ["education.cat.art"] = ("San'at", "Art"),
            ["education.cat.other"] = ("Boshqa", "Other"),
            ["education.center_soon"] = ("{0}: darslar tez orada boshlanadi", "{0}: classes start soon"),

            // ---------------- Biznes markazi
            ["business.title"] = ("Biznes markazi", "Business center"),
            ["business.subtitle"] = ("Yangi imkoniyatlar, yangi hamkorliklar", "New opportunities, new partnerships"),
            ["business.cat.main"] = ("Asosiy", "Overview"),
            ["business.cat.offices"] = ("Ofislar", "Offices"),
            ["business.cat.coworking"] = ("Kovorking", "Coworking"),
            ["business.cat.startups"] = ("Startaplar", "Startups"),
            ["business.cat.investors"] = ("Investorlar", "Investors"),
            ["business.cat.events"] = ("Tadbirlar", "Events"),
            ["business.cat.services"] = ("Xizmatlar", "Services"),
            ["business.action.office_rent"] = ("Ofis ijarasi", "Rent an office"),
            ["business.action.find_partner"] = ("Hamkor topish", "Find a partner"),
            ["business.action.post_startup"] = ("Startap joylashtirish", "Post a startup"),
            ["business.action.meet_investors"] = ("Investorlar bilan uchrashuv", "Meet investors"),
            ["business.action.small_office"] = ("Kichik ofis", "Small office"),
            ["business.action.floor"] = ("Butun qavat", "Whole floor"),
            ["business.action.meeting_room"] = ("Majlislar zali", "Meeting room"),
            ["business.action.open_desk"] = ("Ochiq ish joyi", "Open desk"),
            ["business.action.fixed_desk"] = ("Doimiy stol", "Fixed desk"),
            ["business.action.accelerator"] = ("Akselerator", "Accelerator"),
            ["business.action.pitch"] = ("Loyiha taqdimoti", "Pitch day"),
            ["business.action.funds"] = ("Investitsiya fondlari", "Investment funds"),
            ["business.action.networking"] = ("Tanishuv kechasi", "Networking night"),
            ["business.action.legal"] = ("Yuridik yordam", "Legal help"),
            ["business.action.accounting"] = ("Buxgalteriya", "Accounting"),
            ["business.action_soon"] = ("{0}: tez orada", "{0}: coming soon"),

            // ---------------- Ko'ngilochar zona
            ["fun.title"] = ("Ko'ngilochar zona", "Entertainment zone"),
            ["fun.subtitle"] = ("O'yinlar, konsertlar va bayramlar", "Games, concerts and festivals"),
            ["fun.hero.title"] = ("Tadbirlar maydoni", "Event arena"),
            ["fun.hero.subtitle"] = ("Har kuni yangi tadbirlar", "New events every day"),
            ["fun.visit"] = ("Tashrif buyurish", "Visit"),
            ["fun.recommended"] = ("Mashhur joylar", "Popular places"),
            ["fun.cat.all"] = ("Barchasi", "All"),
            ["fun.cat.concerts"] = ("Konsertlar", "Concerts"),
            ["fun.cat.cinema"] = ("Kino", "Cinema"),
            ["fun.cat.games"] = ("O'yinlar", "Games"),
            ["fun.cat.sport"] = ("Sport", "Sport"),
            ["fun.cat.parks"] = ("Istirohat bog'lari", "Parks"),
            ["fun.place.concert_hall"] = ("Konsert zali", "Concert hall"),
            ["fun.place.cinema"] = ("Kinoteatr", "Cinema"),
            ["fun.place.arcade"] = ("O'yinlar zali", "Arcade"),
            ["fun.place.stadium"] = ("Stadion", "Stadium"),
            ["fun.place.park"] = ("Istirohat bog'i", "Amusement park"),
            ["fun.place.club"] = ("Musiqa klubi", "Music club"),

            // ---------------- Do'stlar
            ["friends.title"] = ("Do'stlar va muloqot", "Friends & chat"),
            ["friends.subtitle"] = ("Yangi odamlar bilan tanishing", "Meet new people"),
            ["friends.tab.friends"] = ("Do'stlar", "Friends"),
            ["friends.tab.groups"] = ("Guruhlar", "Groups"),
            ["friends.tab.events"] = ("Tadbirlar", "Events"),
            ["friends.tab.chat"] = ("Chat", "Chat"),
            ["friends.search"] = ("Nickname yoki ID bo'yicha qidirish...", "Search by nickname or ID..."),
            ["friends.suggestions"] = ("Tavsiyalar", "Suggestions"),
            ["friends.hero"] = ("Birga dunyoni kashf eting", "Explore the world together"),
            ["friends.find"] = ("Do'st topish", "Find friends"),
            ["friends.status.online"] = ("Onlayn", "Online"),
            ["friends.status.offline"] = ("Oflayn", "Offline"),
            ["friends.status.friend"] = ("Do'stingiz", "Friend"),
            ["friends.status.outgoing"] = ("So'rov yuborilgan", "Request sent"),
            ["friends.status.incoming"] = ("Sizga so'rov yubordi", "Wants to be friends"),
            ["friends.requests"] = ("Do'stlik so'rovlari", "Friend requests"),
            ["friends.list"] = ("Do'stlaringiz", "Your friends"),
            ["friends.results"] = ("Qidiruv natijalari", "Search results"),
            ["friends.accept"] = ("Qabul qilish", "Accept"),
            ["friends.decline"] = ("Rad etish", "Decline"),
            ["friends.remove"] = ("O'chirish", "Remove"),
            ["friends.request_sent"] = ("{0}: so'rov yuborildi", "Request sent to {0}"),
            ["friends.now_friends"] = ("{0} bilan endi do'stsiz", "You and {0} are now friends"),
            ["friends.removed"] = ("{0} ro'yxatdan olib tashlandi", "{0} was removed"),
            ["friends.requests_disabled"] = ("Bu o'yinchi hozir so'rov qabul qilmaydi", "This player isn't accepting requests"),
            ["friends.too_many"] = ("Javob kutayotgan so'rovlar juda ko'p", "You have too many pending requests"),
            ["friends.empty_suggestions"] = ("Hozircha tavsiyalar yo'q", "No suggestions yet"),
            ["friends.no_results"] = ("Hech kim topilmadi", "No players found"),
            ["friends.no_friends"] = ("Hali do'stlaringiz yo'q. Tavsiyalardan yoki qidiruvdan do'st qo'shing.", "No friends yet. Add someone from suggestions or search."),
            ["friends.groups_soon"] = ("Guruhlar tez orada qo'shiladi", "Groups are coming soon"),
            ["friends.chat_soon"] = ("Chat tez orada qo'shiladi", "Chat is coming soon"),
            ["friends.events_empty"] = ("Yaqin kunlarda tadbir yo'q", "No upcoming events"),

            // ---------------- Top-lar
            ["top.title"] = ("Top-lar", "Leaderboard"),
            ["top.subtitle"] = ("Eng faol o'yinchilar", "The most active players"),
            ["top.scope.all"] = ("Umumiy", "Global"),
            ["top.scope.friends"] = ("Do'stlar orasida", "Among friends"),
            ["top.rank"] = ("O'rin", "Rank"),
            ["top.player"] = ("O'yinchi", "Player"),
            ["top.time"] = ("Onlayn vaqt", "Time online"),
            ["top.me"] = ("Sizning o'rningiz", "Your rank"),
            ["top.hours"] = ("{0} soat {1} daqiqa", "{0} h {1} min"),
            ["top.minutes"] = ("{0} daqiqa", "{0} min"),
            ["top.empty"] = ("Hali reyting yo'q", "No rankings yet"),
            ["top.not_ranked"] = ("Hali reytingda emassiz", "You're not ranked yet"),
            ["top.hint"] = ("Reyting o'yinda o'tkazgan vaqtingiz bo'yicha", "Ranked by time spent in the world"),

            // ---------------- Sozlamalar sahifasi
            ["settings.subtitle"] = ("Hisobingiz va tajribangizni boshqaring", "Manage your account and experience"),
            ["settings.section.profile"] = ("Profil", "Profile"),
            ["settings.section.security"] = ("Xavfsizlik", "Security"),
            ["settings.section.notifications"] = ("Bildirishnomalar", "Notifications"),
            ["settings.section.sound"] = ("Ovoz va grafika", "Sound & graphics"),
            ["settings.section.controls"] = ("Boshqaruv", "Controls"),
            ["settings.section.privacy"] = ("Maxfiylik", "Privacy"),
            ["settings.section.language"] = ("Til", "Language"),
            ["settings.section.help"] = ("Yordam", "Help"),
            ["settings.edit"] = ("Tahrirlash", "Edit"),
            ["settings.row.name"] = ("Ism", "Name"),
            ["settings.row.email"] = ("Email", "Email"),
            ["settings.row.country"] = ("Mamlakat", "Country"),
            ["settings.row.language"] = ("Til", "Language"),
            ["settings.row.style"] = ("Uslub", "Style"),
            ["settings.id"] = ("ID: #{0}", "ID: #{0}"),
            ["settings.email_none"] = ("Kiritilmagan", "Not set"),
            ["settings.email_soon"] = ("Email bilan kirish tez orada qo'shiladi", "Email sign-in is coming soon"),
            ["settings.style_original"] = ("Asl kiyim", "Original"),
            ["settings.style_custom"] = ("O'zimniki", "Custom"),
            ["settings.security.account"] = ("Hisob", "Account"),
            ["settings.security.account_value"] = ("Shu kompyuterda", "On this computer"),
            ["settings.security.login"] = ("Parol bilan kirish", "Password sign-in"),
            ["settings.security.note"] = ("Hisobingiz shu kompyuterda xavfsiz kalit bilan saqlangan. Boshqa kompyuterdan kirish tez orada qo'shiladi.",
                "Your account is stored on this computer with a secure key. Signing in from other computers is coming soon."),
            ["settings.notify.friends"] = ("Do'stlik so'rovlari", "Friend requests"),
            ["settings.notify.events"] = ("Tadbirlar eslatmasi", "Event reminders"),
            ["settings.notify.system"] = ("Tizim xabarlari", "System messages"),
            ["settings.mouse"] = ("Sichqoncha sezgirligi", "Mouse sensitivity"),
            ["settings.invert"] = ("Y o'qini teskari", "Invert Y axis"),
            ["settings.key.move"] = ("Harakat", "Move"),
            ["settings.key.run"] = ("Yugurish", "Run"),
            ["settings.key.jump"] = ("Sakrash", "Jump"),
            ["settings.key.use"] = ("Ishlatish", "Interact"),
            ["settings.key.menu"] = ("Menyu", "Menu"),
            ["settings.privacy.online"] = ("Onlayn holatimni ko'rsatish", "Show my online status"),
            ["settings.privacy.requests"] = ("Do'stlik so'rovlarini qabul qilish", "Accept friend requests"),
            ["settings.privacy.note"] = ("O'chirilsa, boshqalar sizni onlayn ko'rmaydi va reytingda ko'rinmaysiz.", "When off, others won't see you online and you won't appear on the leaderboard."),
            ["settings.help.text"] = ("Qahramonni sichqoncha bilan aylantiring. Yuqoridagi bo'limlar orqali dunyo xaritasi, do'stlar va reytingni oching. Kiyimlar - profil menyusidagi Garderobda. Esc - orqaga yoki chiqish.",
                "Drag the character to rotate it. Use the tabs at the top to open the world map, friends and the leaderboard. Clothes are in the Wardrobe (profile menu). Esc goes back or quits."),
            ["settings.version"] = ("Versiya {0}", "Version {0}"),
            ["settings.saved"] = ("Saqlandi", "Saved"),
            ["country.UZ"] = ("O'zbekiston", "Uzbekistan"),
            ["country.KZ"] = ("Qozog'iston", "Kazakhstan"),
            ["country.KG"] = ("Qirg'iziston", "Kyrgyzstan"),
            ["country.TJ"] = ("Tojikiston", "Tajikistan"),
            ["country.TM"] = ("Turkmaniston", "Turkmenistan"),
            ["country.RU"] = ("Rossiya", "Russia"),
            ["country.TR"] = ("Turkiya", "Turkey"),
            ["country.AE"] = ("BAA", "UAE"),
            ["country.KR"] = ("Koreya", "Korea"),
            ["country.DE"] = ("Germaniya", "Germany"),
            ["country.GB"] = ("Buyuk Britaniya", "United Kingdom"),
            ["country.US"] = ("AQSH", "USA"),

            // ---------------- Zonalar
            ["zone.shops"] = ("Magazinlar", "Shops"),
            ["zone.shops.sub"] = ("Xarid va do'konlar", "Shopping and stores"),
            ["zone.education"] = ("O'quv markazlari", "Education centers"),
            ["zone.education.sub"] = ("Bilim va rivojlanish", "Learning and growth"),
            ["zone.business"] = ("Biznes markazi", "Business center"),
            ["zone.business.sub"] = ("Ish va hamkorlik", "Work and partnership"),
            ["zone.entertainment"] = ("Ko'ngilochar zona", "Entertainment zone"),
            ["zone.entertainment.sub"] = ("O'yin va tadbirlar", "Games and events"),
            ["zone.community"] = ("Hamjamiyat", "Community"),
            ["zone.community.sub"] = ("Do'stlar va muloqot", "Friends and chat"),

            // ---------------- Sozlamalar
            ["settings.title"] = ("Sozlamalar", "Settings"),
            ["settings.display"] = ("Ekran rejimi", "Display mode"),
            ["settings.size"] = ("Oyna o'lchami", "Window size"),
            ["settings.quality"] = ("Grafika sifati", "Graphics quality"),
            ["settings.vsync"] = ("V-Sync", "V-Sync"),
            ["settings.volume"] = ("Ovoz", "Volume"),
            ["settings.language"] = ("Til", "Language"),
            ["settings.fullscreen"] = ("To'liq ekran", "Fullscreen"),
            ["settings.windowed"] = ("Oynali", "Windowed"),
            ["settings.on"] = ("Yoqilgan", "On"),
            ["settings.off"] = ("O'chiq", "Off"),
            ["settings.done"] = ("Tayyor", "Done"),
            ["quality.0"] = ("Juda past", "Very low"),
            ["quality.1"] = ("Past", "Low"),
            ["quality.2"] = ("O'rta", "Medium"),
            ["quality.3"] = ("Yuqori", "High"),
            ["quality.4"] = ("Juda yuqori", "Very high"),
            ["quality.5"] = ("Ultra", "Ultra"),

            // ---------------- Qahramon yaratish
            ["create.eyebrow"] = ("YANGI O'YINCHI", "NEW PLAYER"),
            ["create.title"] = ("Qahramoningizni\nyarating", "Create your\ncharacter"),
            ["create.subtitle"] = ("Nickname va avatar tanlang, keyin rasmdan yuzingizni qo'shing.", "Pick a nickname and an avatar, then add your face from a photo."),
            ["edit.eyebrow"] = ("SOZLASH", "CUSTOMIZE"),
            ["edit.title"] = ("Qahramonni\nsozlash", "Edit your\ncharacter"),
            ["edit.subtitle"] = ("Boshqa avatar tanlang yoki yuzingizni yangilang.", "Choose another avatar or update your face."),
            ["create.gender_male"] = ("Erkak · pasportdan", "Male · from passport"),
            ["create.gender_female"] = ("Ayol · pasportdan", "Female · from passport"),
            ["create.nickname"] = ("NICKNAME", "NICKNAME"),
            ["create.nickname_placeholder"] = ("Nickname kiriting", "Enter a nickname"),
            ["create.your_nickname"] = ("Sizning nickname", "Your nickname"),
            ["create.avatar"] = ("AVATAR", "AVATAR"),
            ["create.face"] = ("YUZ", "FACE"),
            ["create.help_default"] = ("3–16 belgi: harflar, raqamlar va _. Harf bilan boshlanadi.", "3–16 characters: letters, numbers and _. Starts with a letter."),
            ["create.checking"] = ("Tekshirilmoqda…", "Checking availability…"),
            ["create.available"] = ("Nickname bo'sh", "Nickname is available"),
            ["create.taken"] = ("Bu nickname band.", "This nickname is already taken."),
            ["create.taken_race"] = ("Kimdir hozirgina bu nickname'ni oldi. Boshqasini tanlang.", "Someone just took this nickname. Try another one."),
            ["create.invalid"] = ("Bu nickname'ni ishlatib bo'lmaydi.", "This nickname can't be used."),
            ["create.length"] = ("3–16 ta belgi bo'lishi kerak.", "Use 3–16 characters."),
            ["create.pattern"] = ("Harf bilan boshlang. Faqat lotin harflari, raqamlar va _.", "Start with a letter. Use only letters, numbers and _."),
            ["create.reserved"] = ("Bu nom band qilingan.", "This name is reserved."),
            ["create.offline"] = ("Serverga ulanib bo'lmadi. Qayta urinilmoqda…", "Can't reach the server. Retrying…"),
            ["create.create"] = ("Qahramon yaratish", "Create character"),
            ["create.creating"] = ("Yaratilmoqda…", "Creating…"),
            ["create.welcome"] = ("Xush kelibsiz, {0}", "Welcome, {0}"),
            ["create.save"] = ("Saqlash", "Save changes"),
            ["create.saving"] = ("Saqlanmoqda…", "Saving…"),
            ["create.saved"] = ("Saqlandi", "Saved"),
            ["create.nickname_locked"] = ("Nickname'ni o'zgartirib bo'lmaydi.", "Your nickname can't be changed."),
            ["create.error_network"] = ("Serverga ulanib bo'lmadi. Internetni tekshirib, qayta urining.", "Can't reach the server. Check your connection and try again."),
            ["create.error_avatar"] = ("Bu avatar pasport ma'lumotlaringizga mos emas.", "This avatar doesn't match your passport data."),
            ["create.error_limit"] = ("Juda ko'p urinish. Bir daqiqa kutib, qayta urining.", "Too many attempts. Wait a minute and try again."),
            ["create.error_server"] = ("Serverda xato yuz berdi. Qayta urining.", "Something went wrong on the server. Try again."),
            ["create.error_profile"] = ("Profilingiz serverda topilmadi.", "Your profile was not found on the server."),
            ["create.drag_hint"] = ("Aylantirish uchun torting · Yaqinlashtirish uchun g'ildirak", "Drag to rotate · Scroll to zoom"),
            ["create.view_front"] = ("Old", "Front"),
            ["create.view_side"] = ("Yon", "Side"),
            ["create.view_back"] = ("Orqa", "Back"),
            ["create.quit_message"] = ("Qahramon hali yaratilmadi. Chiqmoqchimisiz?", "Your character is not created yet. Are you sure you want to quit?"),

            // ---------------- Avatarlar
            ["avatar.info"] = ("{0} · {1} sm", "{0} · {1} cm"),
            ["avatar.athletic"] = ("Atletik", "Athletic"),
            ["avatar.slim"] = ("Ozg'in", "Slim"),
            ["avatar.strong"] = ("Baquvvat", "Strong"),
            ["avatar.classic"] = ("Klassik", "Classic"),
            ["avatar.sporty"] = ("Sportcha", "Sporty"),
            ["avatar.petite"] = ("Nozik", "Petite"),
            ["avatar.casual"] = ("Oddiy", "Casual"),
            ["avatar.tall"] = ("Baland bo'yli", "Tall"),
            ["avatar.elegant"] = ("Nafis", "Elegant"),

            // ---------------- Yuz
            ["face.take"] = ("Suratga olish", "Take photo"),
            ["face.upload"] = ("Rasm yuklash", "Upload photo"),
            ["face.hint"] = ("Kameraga to'g'ri qarang, yorug' joyda, ko'zoynaksiz.", "Look straight at the camera, good light, no glasses."),
            ["face.on_avatar"] = ("Yuzingiz qahramonga qo'yilgan.", "Your face is on the avatar."),
            ["face.added"] = ("Yuz qo'shildi. G'ildirak bilan yaqinlashtiring.", "Face added. Scroll to zoom in or out."),
            ["face.finding"] = ("Yuz qidirilmoqda…", "Finding your face…"),
            ["face.no_camera"] = ("Kamera topilmadi. Rasm yuklang.", "No camera found. Upload a photo instead."),
            ["face.bad_file"] = ("Faylni ochib bo'lmadi. JPG yoki PNG rasm tanlang.", "Can't open this file. Use a JPG or PNG photo."),
            ["face.not_found"] = ("Yuz topilmadi. Yuz aniq ko'rinadigan, yorug' rasm tanlang.", "No face found. Use a clear, front-facing photo with good light."),
            ["face.not_clear"] = ("Yuz yetarlicha aniq emas. Kameraga to'g'ri qarang.", "The face is not clear enough. Look straight at the camera."),
            ["face.error"] = ("Nimadir xato ketdi. Boshqa rasm bilan urining.", "Something went wrong. Try another photo."),
            ["face.modal_title"] = ("Suratga olish", "Take a photo"),
            ["face.modal_hint"] = ("Yuzingizni oval ichiga joylang va to'g'ri qarang.", "Fit your face inside the oval and look straight."),
            ["face.camera_starting"] = ("Kamera yoqilmoqda…", "The camera is starting…"),
            ["face.capture"] = ("Suratga olish", "Capture"),
            ["face.dialog_title"] = ("Yuzingiz rasmini tanlang", "Choose a photo of your face"),
        };
    }
}
